### ISSUE TITLE
Real directory 

### ISSUE THREAD

**Issue by NarendranM08** [cHo0s3N/DeepFake-Videos-Detection#2]
Do we have to add real videos manually by ourselves

**Comment by cHo0s3N** [comment]
> Do we have to add real videos manually by ourselves

Hi @NarendranM08 
I'm not sure that I got what you mean by saying manually, but you have to note that for the real videos, you must have a clear dataset contain both fake/real videos and create a metadata for them, no matter how you collected them. 
Note that you may use a prepared dataset or just collecting videos from different sources, that's all under the preparation step before using the dataset to train our model.

**Comment by NarendranM08** [comment]
path_REAL = 'Path to the directory of REAL samples videos'
Does the above code mean that I have to create a directory for real videos and add its path in th above line of code

**Comment by cHo0s3N** [comment]
> path_REAL = 'Path to the directory of REAL samples videos' Does the above code mean that I have to create a directory for real videos and add its path in th above line of code

you got it correctly! if you just have a bunch of real videos, all what you have to do is to create a directory and move these videos into it and then add its path and let the code do the job!

**Comment by NarendranM08** [comment]
How about this dataset for fake and real videos
https://www.kaggle.com/c/deepfake-detection-challenge/data?msclkid=0ea87026c11211ecadc1175e9921dfd6

**Comment by cHo0s3N** [comment]
> How about this dataset for fake and real videos https://www.kaggle.com/c/deepfake-detection-challenge/data?msclkid=0ea87026c11211ecadc1175e9921dfd6

Note that this code is customized for renaming and creating metadata for a dataset with two directories containing the fake and the real videos.
For the dataset above it will be a little bit complicated if you want to use our code on it, but one thing that you can do is to check the JSON file under the 'train_sample_videos', and distribute the videos after downloading them into their original directories, either 'fake' or 'real', by mapping them to their original label in the JSON file. This will produce two directories containing your training videos, so you can rename it and create metadata for them to work correctly with the further steps.

Note that after implementing the preparation code on your data, you have then to move all of the renamed videos under one directory along with their metadata file.
